[package]
name = "kmeans"
version = "0.1.0"
authors = ["Rodrigo Sousa <rod_sousa@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "*"
plotlib = "0.5.1"